@startuml

title __TILES's Class Diagram__\n

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.AirTile {
          + AirTile()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.GrassTile {
          + GrassTile()
          + IsSolid()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.MountainTile {
          + IsSolid()
          + MountainTile()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.SoilTile {
          + IsSolid()
          + SoilTile()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.Tile {
          {static} + TILE_HEIGHT : int
          {static} + TILE_WIDTH : int
          {static} + airTile : Tile
          {static} + grassTile : Tile
          {static} + soilTile : Tile
          {static} + tiles : Tile[]
          # id : int
          # img : BufferedImage
          {static} - NO_TILES : int
          + Draw()
          + GetId()
          + IsSolid()
          + Tile()
          + Update()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.TreeTile {
          + IsSolid()
          + TreeTile()
      }
    }
  }
  

  namespace PaooGame {
    namespace Tiles {
      class PaooGame.Tiles.WaterTile {
          + IsSolid()
          + WaterTile()
      }
    }
  }
  

  PaooGame.Tiles.AirTile -up-|> PaooGame.Tiles.Tile
  PaooGame.Tiles.GrassTile -up-|> PaooGame.Tiles.Tile
  PaooGame.Tiles.MountainTile -up-|> PaooGame.Tiles.Tile
  PaooGame.Tiles.SoilTile -up-|> PaooGame.Tiles.Tile
  PaooGame.Tiles.TreeTile -up-|> PaooGame.Tiles.Tile
  PaooGame.Tiles.WaterTile -up-|> PaooGame.Tiles.Tile


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
